export const myConfig ={
    des:'站点基本信息',
    footer:'订单查询demo',
    brand:'订单查询demo',
    fetch_url:'http://139.129.58.131:3006/',
    pages:[
        {
            des:'',
            teamid:'1',
            1:[
            {
                des:'',
                title:'',
            },
            {
                des:'',                
                title:'',
            },
            ]
        },
        {
            des:'',
            teamid:'',
            1:[
            {
                des:'',
                title:'',
            },
            {
                des:'',                
                title:'',
            },
            ]
        },
        {
            des:'订单查询',
            teamid:'3',
            1:[
            {
                des:'',
                title:'',
            },
            {
                des:'',                
                title:'',
            },
            ]
        },
        {
            des:'',
            teamid:'4',
            1:[
            {
                des:'',
                title:'',
            },
            {
                des:'',                
                title:'',
            },
            ]
        },
        {
            des:'测试页面',
            teamid:'5',
        },
    ]};